#Docker compose file version
version: '3.8'
#Name of docker network
networks:
  mono-net:
#List of docker services
services:
  #Service name
  mysql-service:
    #Image name
    image: mysql-img:v1
    #MySQL environment variables
    environment:
      MYSQL_ROOT_PASSWORD: root
    #Restart policy        
    restart: always
    #Docker network used
    networks:
      - mono-net
    #Name of docker container
    container_name: mysql-con
  
  #Service name
  mono-service:
    #Image name  
    image: mono-img:latest
    #Restart policy    
    restart: always
    #Port binding   
    ports:
      - 8080:8080
    #Docker network used
    networks:
       - mono-net
    #Name of docker container
    container_name: mono-con
