#Docker compose file version
version: '3.8'
#Name of docker network
networks:
  mono-net:
#List of docker services
services:
  #Service name
  mysql-service:
    #Image name
    image: 1820441/infy-mysql:v1
    #MySQL environment variables
    environment:
      MYSQL_ROOT_PASSWORD: root
    #Restart policy        
    restart: always
    #Docker network used
    networks:
      - mono-net
    #Name of docker container
    container_name: mysql-mono-con
  
  #Service name
  mono-service:
    #Image name  
    image: 1820441/spring-boot:v3
    #Restart policy    
    restart: always
    #Port binding   
    ports:
      - 8080:8080
      # - 8080-8085:8080 # You can use multiple instance in this way by adding multiple ports and by removing container name
    #Docker network used
    networks:
       - mono-net
    #Name of docker container
    container_name: mono-con
